### ISSUE TITLE
アプリケーションをOBSのプラグインにする

### ISSUE THREAD

**Issue by takenokoroid** [sanzukawa/PythonCommentViewer#1]
# 概要
PythonCommentViewerをOBSのプラグインにする

# 背景・目的
依頼主からPythonCommentViewerのUX向上を求められたため。

PythonCommentViewerはCLI操作・ブラウザの多重起動によって利用者に大きな負担をかける設計になっていた。
それらを改善し、より手軽に起動・操作できるアプリにしたい。

# 提案
アプリをOBSのプラグインにする。
それによりOBSからの起動や変数の変更が可能になり、UXの向上につながる。

# タスク
- [ ] 工事中

# 備考
とりあえず知見共有も兼ねて作りました。
参考サイトなどを貼っていく想定です。

**Comment by takenokoroid** [comment]
@sanzukawa 
軽く調べてた程度ですが、よい参考サイト見当たりませんね。
なにかありましたら共有いただけるとうれしいです。

あとプラグインというよりスクリプトをイメージされていますか？
https://obsproject.com/docs/scripting.html

**Comment by sanzukawa** [comment]
そうですね
スクリプト化のブランチ作ったのでそっちも覗いてみてください

**Comment by takenokoroid** [comment]
ありがとうございます
#2 の方進めながら見ておきます

**Comment by sanzukawa** [comment]
スクリプト化ですが厳しそうなので諦めてexe化にしようかなと
ブラウザの多重起動は現時点で解決しているので、exe化すればCLI操作は不要になるので
